### ISSUE TITLE
Unable to send to some accounts created by Agora

### ISSUE THREAD

**Issue by showered** [kin-labs/kinetic-android-sdk#25]
This was fixed in the Typescript SDK (https://github.com/kin-labs/kinetic/pull/547). Please implement the same in Android. Thank you!

**Comment by beeman** [comment]
It looks like #24 adds this:

> Adds support for transfers to nonstandard token account addresses

**Comment by showered** [comment]
Amazing! Thanks @beeman and @samdowd .

I'll test it out tomorrow and close the issue assuming it works 👍

**Comment by showered** [comment]
It works! Closing the issue.
